"""initial migration

Revision ID: f1af19685697
Revises: 
Create Date: 2026-08-03 11:07:26.704685

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f1af19685697'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('qa_plans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('requirement_or_user_story', sa.Text(), nullable=False),
    sa.Column('implementation_summary', sa.Text(), nullable=True),
    sa.Column('assumptions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'REVIEWED', 'APPROVED', 'ARCHIVED', name='planstatus', native_enum=False), nullable=False),
    sa.Column('current_version', sa.Integer(), nullable=False),
    sa.Column('coverage_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('acceptance_criteria',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('qa_plan_id', sa.UUID(), nullable=False),
    sa.Column('identifier', sa.String(length=50), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['qa_plan_id'], ['qa_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_acceptance_criteria_qa_plan_id'), 'acceptance_criteria', ['qa_plan_id'], unique=False)
    op.create_table('execution_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('qa_plan_id', sa.UUID(), nullable=False),
    sa.Column('node', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['qa_plan_id'], ['qa_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_execution_logs_qa_plan_id'), 'execution_logs', ['qa_plan_id'], unique=False)
    op.create_table('qa_plan_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('qa_plan_id', sa.UUID(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('change_summary', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['qa_plan_id'], ['qa_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_qa_plan_versions_qa_plan_id'), 'qa_plan_versions', ['qa_plan_id'], unique=False)
    op.create_table('test_cases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('qa_plan_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('test_type', sa.Enum('UNIT', 'API', 'INTEGRATION', 'E2E', 'PLAYWRIGHT', 'MANUAL', name='testtype', native_enum=False), nullable=False),
    sa.Column('category', sa.Enum('HAPPY_PATH', 'EDGE_CASE', 'PERMISSION', 'FAILURE_STATE', 'REGRESSION', name='testcategory', native_enum=False), nullable=False),
    sa.Column('acceptance_criteria_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('steps', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('expected_result', sa.Text(), nullable=False),
    sa.Column('preconditions', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PROPOSED', 'APPROVED', 'REJECTED', 'EDITED', name='teststatus', native_enum=False), nullable=False),
    sa.Column('priority', sa.Enum('CRITICAL', 'HIGH', 'MEDIUM', 'LOW', name='testpriority', native_enum=False), nullable=False),
    sa.Column('is_duplicate', sa.Boolean(), nullable=False),
    sa.Column('is_incomplete', sa.Boolean(), nullable=False),
    sa.Column('flag_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['qa_plan_id'], ['qa_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_cases_qa_plan_id'), 'test_cases', ['qa_plan_id'], unique=False)
    op.create_table('test_reviews',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('test_case_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.Enum('APPROVED', 'REJECTED', 'EDITED', 'PRIORITY_CHANGED', 'STATUS_CHANGED', name='reviewaction', native_enum=False), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('previous_state', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_state', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['test_case_id'], ['test_cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_reviews_test_case_id'), 'test_reviews', ['test_case_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_test_reviews_test_case_id'), table_name='test_reviews')
    op.drop_table('test_reviews')
    op.drop_index(op.f('ix_test_cases_qa_plan_id'), table_name='test_cases')
    op.drop_table('test_cases')
    op.drop_index(op.f('ix_qa_plan_versions_qa_plan_id'), table_name='qa_plan_versions')
    op.drop_table('qa_plan_versions')
    op.drop_index(op.f('ix_execution_logs_qa_plan_id'), table_name='execution_logs')
    op.drop_table('execution_logs')
    op.drop_index(op.f('ix_acceptance_criteria_qa_plan_id'), table_name='acceptance_criteria')
    op.drop_table('acceptance_criteria')
    op.drop_table('qa_plans')
    # ### end Alembic commands ###
